### ISSUE TITLE
Incorrect Email Sending Multi-Site Install

### ISSUE THREAD

**Issue by beckbailey** [ryssbowh/craft-triggers#9]
I am using Triggers & Emails in a multi-site install. I have a channel that is utilized by both sites (Discussion Boards). I have a trigger and an email defined for each site and have attached screenshots of the configurations.

Using my front end form things work as expected. The proper email goes out. However, if I add an entry to the section from the site that is not primary, in the CP, the notification for the primary site goes out. I set up a test of using a section that was only assigned to the non-primary site and no email sent. 

**To Reproduce**
1. Set Up Craft Multi Install
2. Set Up a Channel Section that is shared between sites
3. Set Up a Trigger on entry save for each site (I've used 1 trigger as well with the same result)
4. Set Up a Email for each site
5. Add a entry to the channel section for the non-primary site in the CP that should trigger the non-primary site email.

**Versions: **
 - PHP: 8.0.26
 - Triggers: 1.14
 - Emails: 1.5.0
 - Craft CMS: 3.8.16

[triggers-emails.zip](https://github.com/ryssbowh/craft-triggers/files/13720865/triggers-emails.zip)

**Comment by ryssbowh** [comment]
This seems "normal" to me given what the "site" condition does : It looks at the current site.

On a frontend request the current site would change. On a console or cp request the current site is always the same, it's the primary one.

What I can do is add a new condition "element site" that would look at in which site the element is saved in, that might solve your issue except for 2 things : 
- If you use a different template for your emails it still won't work, the template used for it would always be loaded from the primary site templates.
I would tend to think that it's a separate issue related to emails themselves, and adding an "element site" condition is useful nonetheless.
- When you save an entry, it will save it for all the sites it's available in, so the trigger gets activated as many times.
I just tried that with a "element site" condition, the emails sent are correct, but they are sent twice (because my entry is active in 2 sites)

**Comment by ryssbowh** [comment]
So that's in 1.1.5.
Let me know if that solves your issues

**Comment by beckbailey** [comment]
Thank you for the update. Unfortunately that didn't work. My entries are not shared between sites. The sites share the section to simplify templating. I don't necessarily need separate email templates if the system pulls the correct entry information in the email. I want the email to use information from the entry saved most recently in the Discussion Boards section from the proper site. I had created 2 separate email templates (one for each site) to attempt to solve that by changing the entry query to use the site handle.

Single Email Set Up For Multi-Sites
`{% set entry = craft.entries.section('discussionBoards').one() %}`

Separate Email Set Up Using Site Handle
`{% set entry = craft.entries.section('discussionBoards').site('secondarySiteHandle').one() %}`

I tried your most recent update using a single email template and separate email templates. Unfortunately it didn't work either way. When I save an entry in the CP on the secondary site, the email pulls the entry info from the primary site. 

I thought I could solve this by creating separate section for the secondary site's entries that is not enabled on the primary site. I tried testing this using the single email and no email sends at all. So it seems like there could be a bug? Perhaps I should have listed this on the Emails plugin instead of the Triggers plugin?

**Comment by ryssbowh** [comment]
@beckbailey Have you replaced your site condition with the new element site condition on your test ?

**Comment by beckbailey** [comment]
> @beckbailey Have you replaced your site condition with the new element site condition on your test ?

Yes, this is the latest configuration I've tested with the section that is only assigned to the secondary site. This results in no email being sent. I'm using the query {% set entry = craft.entries.section('appTest').one() %} to get the entry info in my email template.

<img width="838" alt="updated-config" src="https://github.com/ryssbowh/craft-triggers/assets/1824287/65540bbc-a113-404b-9c49-5783c6da78dc">

**Comment by ryssbowh** [comment]
@beckbailey you would need to remove the first "Site" condition as this will always resolve to the primary one on a cp request

**Comment by beckbailey** [comment]
> @beckbailey you would need to remove the first "Site" condition as this will always resolve to the primary one on a cp request

Thank you. That solved my issue.
